import { useWorkflowCopilotPlanning } from "../copilot/useWorkflowCopilotPlanning.ts";
import { useWorkflowRunController } from "../runtime/useWorkflowRunController.ts";
import { useAgentConversationBridge } from "../copilot/useAgentConversationBridge.ts";
import { useWorkflowLocalSnapshotController } from "./useWorkflowLocalSnapshotController.ts";
import { useWorkflowGraphMutationController } from "../graph/useWorkflowGraphMutationController.ts";
import { defaultAdRequest, demoEdges, demoNodes } from "./workflowPageDefaults.ts";

// Adapter value bag used while the page model is being decomposed into stable controllers.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type WorkflowPageRunGraphControllersArgs = Record<string, any>;

export function useWorkflowPageRunGraphControllers(args: WorkflowPageRunGraphControllersArgs) {
  const copilotPlanning = useWorkflowCopilotPlanning({
    messages: args.messages,
    workflowPrompt: args.workflowPrompt,
    adRequest: args.adRequest,
    promptLibraryEntities: args.promptLibraryEntities,
    selectedAssets: args.selectedAssets,
    workflowPromptAssetReferences: args.workflowPromptAssetReferences,
    beginWorkflowMutationScope: args.beginWorkflowMutationScope,
    shouldApplyWorkflowMutationScope: args.shouldApplyWorkflowMutationScope,
    setMessages: args.setMessages,
    setStatus: args.setStatus,
    syncFrontDeskAdRequest: args.syncFrontDeskAdRequest,
    applyWorkflowV2: args.applyWorkflowV2,
    bridgeFrontDeskMessagesToAgentConversation: (requestWorkflowId, plannedMessages) =>
      args.bridgeFrontDeskMessagesToAgentConversationRef.current?.(requestWorkflowId, plannedMessages) ?? Promise.resolve(),
  });
  const { askCopilot, uploadV2PromptInputAsset, v2PlanFromPromptRequest } = copilotPlanning.actions;

  const workflowRunController = useWorkflowRunController({
    defaultAdRequest,
    workflow: args.workflow,
    canvasNodes: args.canvasNodes,
    visibleCanvasNodes: args.visibleCanvasNodes,
    flowNodes: args.flowNodes,
    flowEdges: args.flowEdges,
    selectedAssets: args.selectedAssets,
    selectedPlanNode: args.selectedPlanNode,
    selectedRunType: args.selectedRunType,
    selectedResolvedInputs: args.selectedResolvedInputs,
    nodeRuns: args.nodeRuns,
    workflowVariables: args.workflowVariables,
    runSettings: args.runSettings,
    adRequest: args.adRequest,
    workflowPrompt: args.workflowPrompt,
    messages: args.messages,
    promptLibraryEntities: args.promptLibraryEntities,
    promptPrimaryReferenceIds: args.promptPrimaryReferenceIds,
    nodeRunLibraryEntities: args.nodeRunLibraryEntities,
    overridePrompt: args.overridePrompt,
    currentNodeRunning: args.currentNodeRunning,
    activeWorkflowIdRef: args.activeWorkflowIdRef,
    currentNodeRunningRef: args.currentNodeRunningRef,
    currentNodeRunRequestRef: args.currentNodeRunRequestRef,
    setActiveExecutionId: args.setActiveExecutionId,
    setExecutionNodeStatusById: args.setExecutionNodeStatusById,
    setRunningNodeIds: args.setRunningNodeIds,
    setExecutionPollingState: args.setExecutionPollingState,
    setWorkflowRunning: args.setWorkflowRunning,
    setWorkflowRun: args.setWorkflowRun,
    setMediaStatus: args.setMediaStatus,
    setStatus: args.setStatus,
    setCanvasNodes: args.setCanvasNodes,
    setFlowNodes: args.setFlowNodes,
    setMessages: args.setMessages,
    setAdRequest: args.setAdRequest,
    setCurrentNodeRunning: args.setCurrentNodeRunning,
    setSelectedNodeRun: args.setSelectedNodeRun,
    setSelectedResolvedInputs: args.setSelectedResolvedInputs,
    setWorkflow: args.setWorkflow,
    currentWorkflowIsV2: args.currentWorkflowIsV2,
    assertNotV2WorkflowForV1Api: args.assertNotV2WorkflowForV1Api,
    beginWorkflowMutationScope: args.beginWorkflowMutationScope,
    shouldApplyWorkflowMutationScope: args.shouldApplyWorkflowMutationScope,
    workflowPromptAssetReferences: args.workflowPromptAssetReferences,
    syncFrontDeskAdRequest: args.syncFrontDeskAdRequest,
    applyWorkflowV2: args.applyWorkflowV2,
    v2PlanFromPromptRequest,
    syncV2Events: (requestWorkflowId) => args.v2Runtime.syncEvents(requestWorkflowId),
    syncV2Snapshot: (requestWorkflowId) => args.v2Runtime.syncSnapshot(requestWorkflowId),
    flushV2SlotDrafts: args.flushV2SlotDrafts,
    runV2Workflow: args.workflowV2Controller.actions.runWorkflow,
    refreshV2AssetsAndRetryMissing: args.refreshV2AssetsAndRetryMissing,
    saveCanvas: args.saveCanvas,
    validateBackendGraph: args.validateBackendGraph,
    prepareFinalCompositionRun: args.prepareFinalCompositionRun,
    refreshWorkflowNodes: args.refreshWorkflowNodes,
    refreshWorkflowGraph: args.refreshWorkflowGraph,
    refreshMediaStatus: args.refreshMediaStatus,
    refreshSelectedResolvedInputs: args.refreshSelectedResolvedInputs,
    patchWorkflowNodeState: args.patchWorkflowNodeState,
    shouldApplyCurrentNodeRun: args.shouldApplyCurrentNodeRun,
    nodeScopedAssetReferences: args.nodeScopedAssetReferences,
    runSelectedV2Slot: args.runSelectedV2Slot,
    pollStoryboardVideoMedia: args.pollStoryboardVideoMedia,
    applyNodeRunsToCanvas: args.applyNodeRunsToCanvas,
    applyMediaStatusToCanvas: args.applyMediaStatusToCanvas,
  });
  args.workflowRunActionsRef.current = workflowRunController.actions;

  const agentConversationBridge = useAgentConversationBridge({
    workflow: args.workflow,
    selectedPlanNode: args.selectedPlanNode,
    activeWorkflowIdRef: args.activeWorkflowIdRef,
    conversation: args.workflowConversation,
    messages: args.messages,
    currentWorkflowIsV2: args.currentWorkflowIsV2,
    getWorkflowNodeType: args.getWorkflowNodeType,
    defaultV2SlotForCurrentNode: args.defaultV2SlotForCurrentNode,
    selectedV2Items: args.selectedV2Items,
    setStatus: args.setStatus,
    askCopilot,
    applyWorkflowV2: args.applyWorkflowV2,
    applyV2RuntimeEventsToPage: args.applyV2RuntimeEventsToPage,
    handleAgentConversationEvents: args.handleAgentConversationEvents,
    queueScopedWorkflowRefresh: args.queueScopedWorkflowRefresh,
  });
  args.bridgeFrontDeskMessagesToAgentConversationRef.current = agentConversationBridge.actions.bridgeFrontDeskMessagesToAgentConversation;

  const localSnapshot = useWorkflowLocalSnapshotController({
    workflowId: args.workflowId,
    canvasNodes: args.canvasNodes,
    flowNodes: args.flowNodes,
    flowEdges: args.flowEdges,
    workflowVariables: args.workflowVariables,
    reactFlow: args.reactFlow,
    activeProjectId: args.activeProjectId,
    isRestoringWorkspace: args.isRestoringWorkspace,
    workflow: args.workflow,
    messages: args.messages,
    nodeRuns: args.nodeRuns,
    selectedAssets: args.selectedAssets,
    promptLibraryEntities: args.promptLibraryEntities,
    saveProject: args.saveProject,
    setSavedAt: args.setSavedAt,
    setStatus: args.setStatus,
  });

  const workflowGraphMutations = useWorkflowGraphMutationController({
    workflow: args.workflow,
    workflowId: args.workflowId,
    demoNodes,
    demoEdges,
    canvasNodes: args.canvasNodes,
    flowNodes: args.flowNodes,
    flowEdges: args.flowEdges,
    nodeRuns: args.nodeRuns,
    nodeRunByType: args.nodeRunByType,
    workflowVariables: args.workflowVariables,
    selectedAssets: args.selectedAssets,
    promptLibraryEntities: args.promptLibraryEntities,
    messages: args.messages,
    selectedPlanNode: args.selectedPlanNode,
    selectedNodeId: args.selectedNodeId,
    selectedEdgeId: args.selectedEdgeId,
    selectedSystemSuggestion: args.selectedSystemSuggestion,
    selectedOptimizedPrompt: args.selectedOptimizedPrompt,
    selectedRunType: args.selectedRunType,
    selectedResolvedInputs: args.selectedResolvedInputs,
    nodeUploadKind: args.nodeUploadKind,
    nodeUploadName: args.nodeUploadName,
    nodeUploadTags: args.nodeUploadTags,
    staleReason: args.staleReason,
    reactFlow: args.reactFlow,
    pendingNodePatches: args.pendingNodePatches,
    activeWorkflowIdRef: args.activeWorkflowIdRef,
    currentNodeRunningRef: args.currentNodeRunningRef,
    currentNodeRunRequestRef: args.currentNodeRunRequestRef,
    setWorkflow: args.setWorkflow,
    setCanvasNodes: args.setCanvasNodes,
    setFlowNodes: args.setFlowNodes,
    setFlowEdges: args.setFlowEdges,
    setWorkflowVariables: args.setWorkflowVariables,
    setSelectedNodeId: args.setSelectedNodeId,
    setSelectedEdgeId: args.setSelectedEdgeId,
    setSelectedNodeRun: args.setSelectedNodeRun,
    setSelectedResolvedInputs: args.setSelectedResolvedInputs,
    setMediaStatus: args.setMediaStatus,
    setWorkflowRun: args.setWorkflowRun,
    setWorkflowRunning: args.setWorkflowRunning,
    setCurrentNodeRunning: args.setCurrentNodeRunning,
    setValidationResult: args.setValidationResult,
    setNodeVersions: args.setNodeVersions,
    setAffectedNodes: args.setAffectedNodes,
    setSavedAt: args.setSavedAt,
    setSaving: args.setSaving,
    setStatus: args.setStatus,
    setDetailsOpen: args.setDetailsOpen,
    setMediaLightbox: args.setMediaLightbox,
    setUploadingAsset: args.setUploadingAsset,
    setVariablesPanelOpen: args.setVariablesPanelOpen,
    currentWorkflowIsV2: args.currentWorkflowIsV2,
    assertNotV2WorkflowForV1Api: args.assertNotV2WorkflowForV1Api,
    refreshV2WorkflowGraph: args.refreshV2WorkflowGraph,
    refreshWorkflowGraph: args.refreshWorkflowGraph,
    refreshNodeVersions: args.refreshNodeVersions,
    refreshSelectedResolvedInputs: args.refreshSelectedResolvedInputs,
    getCurrentRunAdRequest: workflowRunController.actions.getCurrentRunAdRequest,
    nodeScopedAssetReferences: args.nodeScopedAssetReferences,
    applyNodeRunsToCanvas: args.applyNodeRunsToCanvas,
    patchWorkflowNodeState: args.patchWorkflowNodeState,
    markNodesStale: args.markNodesStale,
    noteAffected: args.noteAffected,
    saveProject: args.saveProject,
    startNewProject: args.startNewProject,
    persistLocalSnapshot: localSnapshot.actions.persistLocalSnapshot,
    persistNodePositionSnapshot: localSnapshot.actions.persistNodePositionSnapshot,
    captureCanvasHistory: args.captureCanvasHistory,
    clearCanvasHistory: args.clearCanvasHistory,
    resetExportState: args.resetExportState,
  });
  args.workflowGraphMutationsRef.current = workflowGraphMutations;

  return {
    askCopilot,
    uploadV2PromptInputAsset,
    workflowRunController,
    agentConversationBridge,
    workflowGraphMutations,
    persistLocalSnapshot: localSnapshot.actions.persistLocalSnapshot,
  };
}
