"""Generate deterministic Pi Agent runtime contracts from canonical Pydantic models."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from app.schemas import agent_runtime


CONTRACT_MODELS = (
    agent_runtime.AgentReferenceSummary,
    agent_runtime.AgentTargetContext,
    agent_runtime.AgentRunContext,
    agent_runtime.AgentRunPolicy,
    agent_runtime.AgentRunRequest,
    agent_runtime.AgentRuntimeEvent,
    agent_runtime.AgentToolCall,
    agent_runtime.AgentToolResult,
    agent_runtime.AgentStructuredSubmission,
    agent_runtime.AgentStructuredValidationResult,
    agent_runtime.AgentRuntimeHealth,
    agent_runtime.AgentRuntimeError,
    agent_runtime.SpecialistDraft,
)


def generate_agent_contracts(output_dir: Path) -> tuple[Path, Path]:
    """Write canonical JSON Schema and TypeScript declarations in stable byte order."""

    output_dir.mkdir(parents=True, exist_ok=True)
    combined_schema = TypeAdapter(
        tuple[tuple(CONTRACT_MODELS)]  # type: ignore[valid-type]
    ).json_schema()
    # Pydantic's tuple adapter provides one shared $defs graph for all contracts.
    definitions = combined_schema.get("$defs", {})
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://adcraft.local/contracts/agent-runtime-v1.schema.json",
        "protocol_version": "1",
        "$defs": definitions,
    }
    schema_path = output_dir / "agent-runtime.schema.json"
    schema_path.write_text(
        json.dumps(schema, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    declarations = [
        "/* Generated by app.cli.generate_agent_contracts. Do not edit manually. */",
        "",
        'export const AGENT_PROTOCOL_VERSION = "1" as const;',
        "",
    ]
    for model in CONTRACT_MODELS:
        model_schema = definitions[model.__name__]
        declarations.append(f"export type {model.__name__} = {_typescript_type(model_schema)};")
        declarations.append("")
    typescript_path = output_dir / "agent-runtime.ts"
    typescript_path.write_text("\n".join(declarations), encoding="utf-8")
    return schema_path, typescript_path


def _typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=True)
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=True) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_typescript_type(option) for option in schema["anyOf"])
    schema_type = schema.get("type")
    if schema_type == "object" or "properties" in schema:
        if schema.get("additionalProperties") not in {None, False}:
            additional = schema["additionalProperties"]
            value_type = _typescript_type(additional) if isinstance(additional, dict) else "unknown"
            return f"Readonly<Record<string, {value_type}>>"
        required = frozenset(schema.get("required", []))
        members = []
        for name, member_schema in schema.get("properties", {}).items():
            optional = "" if name in required else "?"
            members.append(
                f"readonly {json.dumps(name)}{optional}: {_typescript_type(member_schema)}"
            )
        return "{ " + "; ".join(members) + " }"
    if schema_type == "array":
        return f"ReadonlyArray<{_typescript_type(schema.get('items', {}))}>"
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    return "unknown"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("agent-runtime/src/generated"),
    )
    arguments = parser.parse_args()
    generate_agent_contracts(arguments.output)


if __name__ == "__main__":
    main()
