export const SNAPSHOT_AUTOSAVE_DELAY_MS = 1800;
export const DEBUG_LIST_PREVIEW_LIMIT = 12;
export const LOCAL_REVISION_HISTORY_PREVIEW_LIMIT = 12;
export const SEMANTIC_GALLERY_PREVIEW_LIMIT = 4;
export const WORKFLOW_CONTROLLER_MAX_LINES = 1500;
