import { expect, test } from "@playwright/test";

test("brand Skills reuse the existing catalog and keep save separate from confirmation", async ({ page }) => {
  const unexpectedApiRequests: string[] = [];
  await page.route(/\/api\/v[12]\//, async (route) => { unexpectedApiRequests.push(route.request().url()); await route.abort(); });
  await page.goto("/tests/browser/brand-skill-picker-mock.html");
  const openButton = page.getByRole("button", { name: "选择 Skills / Choose Skills" });
  await openButton.click();
  const picker = page.getByRole("dialog", { name: "选择品牌 Skills" });
  await expect(picker.getByRole("checkbox")).toHaveCount(7);
  await expect(picker.getByRole("radio")).toHaveCount(3);
  await picker.getByRole("button", { name: "取消", exact: true }).click();
  await expect(openButton).toBeFocused();
  await openButton.click();
  await picker.getByRole("checkbox", { name: /私人仪式/ }).check();
  await picker.getByRole("button", { name: "选择视听风格", exact: true }).click();
  const styles = page.getByRole("dialog", { name: "选择视听风格", exact: true });
  await expect(styles.getByRole("button", { name: /微缩世界/ })).toBeVisible();
  await styles.getByRole("button", { name: /微缩世界/ }).click();
  await expect(styles).not.toBeVisible();
  await expect(picker.getByText("当前选择：微缩世界")).toBeVisible();
  await picker.getByRole("button", { name: "保存", exact: true }).click();
  await expect(picker.getByRole("status")).toContainText("已保存");
  await expect(page.getByTestId("stage")).toHaveText("skill-stack");
  await page.screenshot({ path: "/tmp/adcraft-brand-picker-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(picker).toBeVisible();
  expect(await picker.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: "/tmp/adcraft-brand-picker-mobile.png" });
  await picker.getByRole("button", { name: "确认并继续" }).click();
  await expect(picker).not.toBeVisible();
  await expect(page.getByTestId("stage")).toHaveText("treatment");
  const probe = await page.evaluate(() => (window as unknown as { brandSkillProbe: { writes: Array<{ card_id: string; expected_stage_revision: number; confirm: boolean; creative_methods: unknown[]; audiovisual_style: { skill_id: string } }>; nextQuestions: number; activations: number } }).brandSkillProbe);
  expect(probe.writes).toHaveLength(2);
  expect(probe.writes[0]).toMatchObject({ card_id: "card-5", expected_stage_revision: 5, confirm: false, audiovisual_style: { skill_id: "style-3" } });
  expect(probe.writes[0].creative_methods).toHaveLength(2);
  expect(probe.writes[1]).toMatchObject({ card_id: "card-6", expected_stage_revision: 6, confirm: true });
  expect(probe.nextQuestions).toBe(1);
  expect(probe.activations).toBe(0);
  expect(unexpectedApiRequests).toEqual([]);
});
